package com.sahyadri.sahyadripooltrip.entity;
import jakarta.persistence.*;
@Entity @Table(name="nature_destinations")
public class NatureDestination {
 @Id @Column(name="location_id",nullable=false,unique=true,length=50) private String locationId;
 @Column(nullable=false,length=255) private String name; @Column(nullable=false,length=120) private String state;
 @Column(length=150) private String district; @Column(length=255) private String locality; @Column(length=100) private String category; @Column(length=50) private String section;
 @Column(length=2000) private String description; @Column(name="known_for",length=2000) private String knownFor; private Double latitude; private Double longitude;
 @Column(name="best_season",length=255) private String bestSeason; @Column(length=500) private String difficulty; @Column(name="popularity_tier",length=50) private String popularityTier;
 @Column(name="primary_source",length=500) private String primarySource; @Column(name="photo_source_url",length=1000) private String photoSourceUrl; @Column(name="info_source_url",length=1000) private String infoSourceUrl;
 @Column(name="verification_status",length=500) private String verificationStatus; @Column(name="last_verified",length=50) private String lastVerified; @Column(name="record_status",length=100) private String recordStatus;
 public NatureDestination(){}
 public String getLocationId(){return locationId;} public void setLocationId(String v){locationId=v;} public String getName(){return name;} public void setName(String v){name=v;} public String getState(){return state;} public void setState(String v){state=v;} public String getDistrict(){return district;} public void setDistrict(String v){district=v;} public String getLocality(){return locality;} public void setLocality(String v){locality=v;} public String getCategory(){return category;} public void setCategory(String v){category=v;} public String getSection(){return section;} public void setSection(String v){section=v;} public String getDescription(){return description;} public void setDescription(String v){description=v;} public String getKnownFor(){return knownFor;} public void setKnownFor(String v){knownFor=v;} public Double getLatitude(){return latitude;} public void setLatitude(Double v){latitude=v;} public Double getLongitude(){return longitude;} public void setLongitude(Double v){longitude=v;} public String getBestSeason(){return bestSeason;} public void setBestSeason(String v){bestSeason=v;} public String getDifficulty(){return difficulty;} public void setDifficulty(String v){difficulty=v;} public String getPopularityTier(){return popularityTier;} public void setPopularityTier(String v){popularityTier=v;} public String getPrimarySource(){return primarySource;} public void setPrimarySource(String v){primarySource=v;} public String getPhotoSourceUrl(){return photoSourceUrl;} public void setPhotoSourceUrl(String v){photoSourceUrl=v;} public String getInfoSourceUrl(){return infoSourceUrl;} public void setInfoSourceUrl(String v){infoSourceUrl=v;} public String getVerificationStatus(){return verificationStatus;} public void setVerificationStatus(String v){verificationStatus=v;} public String getLastVerified(){return lastVerified;} public void setLastVerified(String v){lastVerified=v;} public String getRecordStatus(){return recordStatus;} public void setRecordStatus(String v){recordStatus=v;}
}
