package com.sahyadri.sahyadripooltrip.entity;
import java.time.*; import jakarta.persistence.*;
@Entity @Table(name="property_bookings") public class PropertyBooking {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long bookingId; @Column(nullable=false) private Long propertyId; @Column(nullable=false) private Long travelerId; @Column(nullable=false) private Integer roomsBooked; @Column(nullable=false) private Double totalAmount; @Column(nullable=false) private String status; @Column(nullable=false) private LocalDate checkInDate; @Column(nullable=false) private LocalDate checkOutDate; @Column(nullable=false,updatable=false) private LocalDateTime bookedAt;
 private String paymentMethod="PAY_AT_HOTEL"; private String paymentStatus="PAY_AT_HOTEL"; private String couponCode; private Double discountAmount=0.0; private String checkInStatus="NOT_CHECKED_IN"; private String checkOutStatus="NOT_CHECKED_OUT"; private LocalDateTime checkedInAt; private LocalDateTime checkedOutAt;
 @PrePersist protected void onCreate(){bookedAt=LocalDateTime.now(); if(status==null)status="CONFIRMED";}
 public PropertyBooking(){} public Long getBookingId(){return bookingId;} public void setBookingId(Long v){bookingId=v;} public Long getPropertyId(){return propertyId;} public void setPropertyId(Long v){propertyId=v;} public Long getTravelerId(){return travelerId;} public void setTravelerId(Long v){travelerId=v;} public Integer getRoomsBooked(){return roomsBooked;} public void setRoomsBooked(Integer v){roomsBooked=v;} public Double getTotalAmount(){return totalAmount;} public void setTotalAmount(Double v){totalAmount=v;} public String getStatus(){return status;} public void setStatus(String v){status=v;} public LocalDate getCheckInDate(){return checkInDate;} public void setCheckInDate(LocalDate v){checkInDate=v;} public LocalDate getCheckOutDate(){return checkOutDate;} public void setCheckOutDate(LocalDate v){checkOutDate=v;} public LocalDateTime getBookedAt(){return bookedAt;} public void setBookedAt(LocalDateTime v){bookedAt=v;}
 public String getPaymentMethod(){return paymentMethod;} public void setPaymentMethod(String v){paymentMethod=v;} public String getPaymentStatus(){return paymentStatus;} public void setPaymentStatus(String v){paymentStatus=v;} public String getCouponCode(){return couponCode;} public void setCouponCode(String v){couponCode=v;} public Double getDiscountAmount(){return discountAmount;} public void setDiscountAmount(Double v){discountAmount=v;} public String getCheckInStatus(){return checkInStatus;} public void setCheckInStatus(String v){checkInStatus=v;} public String getCheckOutStatus(){return checkOutStatus;} public void setCheckOutStatus(String v){checkOutStatus=v;} public LocalDateTime getCheckedInAt(){return checkedInAt;} public void setCheckedInAt(LocalDateTime v){checkedInAt=v;} public LocalDateTime getCheckedOutAt(){return checkedOutAt;} public void setCheckedOutAt(LocalDateTime v){checkedOutAt=v;}
}
