package com.sahyadri.sahyadripooltrip.dto;
import jakarta.validation.constraints.*;
public class UpdatePropertyRequest {
 @NotBlank private String propertyName; @NotBlank @Pattern(regexp="HOTEL|HOMESTAY",message="Property type must be HOTEL or HOMESTAY") private String propertyType; @NotBlank private String location; private String description; @NotNull @Positive private Integer totalRooms; @NotNull @Positive private Double pricePerNight;
 private String photoUrl; private String checkInTime; private String checkOutTime; private String paymentMode; private String couponCode; private Double couponDiscount; private Double couponMinAmount;
 public UpdatePropertyRequest(){}
 public String getPropertyName(){return propertyName;} public void setPropertyName(String v){propertyName=v;} public String getPropertyType(){return propertyType;} public void setPropertyType(String v){propertyType=v;} public String getLocation(){return location;} public void setLocation(String v){location=v;} public String getDescription(){return description;} public void setDescription(String v){description=v;} public Integer getTotalRooms(){return totalRooms;} public void setTotalRooms(Integer v){totalRooms=v;} public Double getPricePerNight(){return pricePerNight;} public void setPricePerNight(Double v){pricePerNight=v;}
 public String getPhotoUrl(){return photoUrl;} public void setPhotoUrl(String v){photoUrl=v;} public String getCheckInTime(){return checkInTime;} public void setCheckInTime(String v){checkInTime=v;} public String getCheckOutTime(){return checkOutTime;} public void setCheckOutTime(String v){checkOutTime=v;} public String getPaymentMode(){return paymentMode;} public void setPaymentMode(String v){paymentMode=v;} public String getCouponCode(){return couponCode;} public void setCouponCode(String v){couponCode=v;} public Double getCouponDiscount(){return couponDiscount;} public void setCouponDiscount(Double v){couponDiscount=v;} public Double getCouponMinAmount(){return couponMinAmount;} public void setCouponMinAmount(Double v){couponMinAmount=v;}
}
